/**
 * Anchor CPI event log parser for Phalnx.
 *
 * Parses "Program data: " log lines from transaction logs to extract
 * Anchor events. Uses the IDL-provided event discriminators (first 8 bytes
 * of SHA256 of "event:<EventName>").
 *
 * The discriminator map is auto-generated by codama.mjs from the IDL.
 * Run `pnpm run codama` after any Rust event changes.
 */

import { EVENT_DISCRIMINATOR_MAP } from "./generated/event-discriminators.js";

/** All known Phalnx event names */
export type PhalnxEventName = (typeof EVENT_DISCRIMINATOR_MAP)[string];

/** Parsed event from transaction logs */
export interface PhalnxEvent {
  /** Event name (e.g. "VaultCreated", "ActionAuthorized") */
  name: PhalnxEventName;
  /** Raw event data bytes (after discriminator) */
  data: Uint8Array;
}

/**
 * Parse Phalnx Anchor events from transaction logs.
 *
 * Anchor emits events as "Program data: <base64>" log lines.
 * The first 8 bytes are the event discriminator (SHA256 prefix).
 *
 * @param logs - Array of log strings from a transaction
 * @returns Array of parsed events with name and raw data
 */
export function parsePhalnxEvents(logs: string[]): PhalnxEvent[] {
  const events: PhalnxEvent[] = [];
  const PROGRAM_DATA_PREFIX = "Program data: ";

  for (const log of logs) {
    if (!log.includes(PROGRAM_DATA_PREFIX)) continue;

    const dataStart = log.indexOf(PROGRAM_DATA_PREFIX);
    if (dataStart === -1) continue;

    const base64Data = log.slice(dataStart + PROGRAM_DATA_PREFIX.length);

    try {
      const bytes = base64ToBytes(base64Data);
      if (bytes.length < 8) continue;

      // First 8 bytes = discriminator
      const discHex = bytesToHex(bytes.slice(0, 8));
      const eventName = EVENT_DISCRIMINATOR_MAP[discHex];

      if (eventName) {
        events.push({
          name: eventName,
          data: bytes.slice(8),
        });
      }
    } catch {
      // Skip unparseable log lines
    }
  }

  return events;
}

/**
 * Extract events of a specific type from transaction logs.
 */
export function filterEvents(
  logs: string[],
  eventName: PhalnxEventName,
): PhalnxEvent[] {
  return parsePhalnxEvents(logs).filter((e) => e.name === eventName);
}

/** Get all known event names */
export function getEventNames(): PhalnxEventName[] {
  return Object.values(EVENT_DISCRIMINATOR_MAP);
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

function base64ToBytes(base64: string): Uint8Array {
  const binaryString = atob(base64);
  const bytes = new Uint8Array(binaryString.length);
  for (let i = 0; i < binaryString.length; i++) {
    bytes[i] = binaryString.charCodeAt(i);
  }
  return bytes;
}

function bytesToHex(bytes: Uint8Array): string {
  return Array.from(bytes)
    .map((b) => b.toString(16).padStart(2, "0"))
    .join("");
}
